version: '3.8'

services:
  credit-risk-model:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    # Uncomment the following lines to enable Jupyter notebook access
    # ports:
    #   - "8888:8888"
    # command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''